### ISSUE TITLE
No popup on windows

### ISSUE THREAD

**Issue by PixelT** [facelessuser/ColorHelper#16]
When I work on Windows, the popup doesn't show when click on color...
On Mac is OK.
Does anyone else have this?

**Comment by facelessuser** [comment]
I don't know if you have been following, but there **was** an issue with windows.  The Package Control `jinja2` dependency conflicted with the package `Jinja2` due to windows having a case insensitive file system.  Yesterday evening the dependency was renamed to `python-jinja2`.  Even later, I finally updated `ColorHelper` to use the new dependency name.

1. Make sure ColorHelper is upgraded to the latest.
2. Make sure that you see `python-jinja2` in your `Packages` folder.  If you don't run the `Package Control: Satisfy Dependecies` command.
3.  If you have upgraded the package and/or dependecy, a restart may be required.

If it is still not working:

1. Check your console for errors.  Post them here.
2. Remember that ColorHelper searches [certain scopes](http://facelessuser.github.io/ColorHelper/usage/#supported_syntax) in certain files.  In the ColorHelper settings file, you can add new scopes for certain files, but remember that it will work and perform best if you keep the scope narrow.

If you have done all these things, and are seeing no errors in the console, I will ask that you provide an example: source code and point me at what syntax highlighter you are suing for that file.

**Comment by zackdouglas** [comment]
Happened to me 10 minutes ago. Perhaps Package Control hasn't received an update?

**Comment by facelessuser** [comment]
@zackdouglas, did you do any of the steps I gave @PixelT?  If so, what did you find?  I'd love to be more help, but I need to know what you've tried.

**Comment by facelessuser** [comment]
By the way, I am on Windows.

**Comment by facelessuser** [comment]
Also, what do you mean 10 minutes ago?  Was it working, and then stopped?  If so, I would try to restart sublime as PC might have updated things, but needs a restart.

**Comment by PixelT** [comment]
@facelessuser today I'm testing some scenarios.
Now I'm not sure is a platform issue (Windows/Mac), because in the morning I try it on Mac an the popup work (on less files) but on sass not
Im using SCSS package: https://packagecontrol.io/packages/SCSS
I use your step in post above and the problem is in the last step (scopes)
Im adding new scopes for the SCSS package
```
"meta.property-list.scss -comment -string"
```
work on mac, but not on windows? 
I added also:
```
"source.scss -comment -string"
```
and they work now on Windows. Finally, I added this lines:
```
"meta.property-list.scss -comment -string"
"source.scss -comment -string"
```
and the work on Windows and Mac (on Less and Sass files)

The SCSS package (https://packagecontrol.io/packages/SCSS) is very popular (TOP25), so maybe it's a good option to add scope for this package in default settings?

---
Another bug? / problem is, I don't have ColorHelper settings in ST menu (Preferences -> Packages Settings -> [no ColorHelper]
Im addig color_helper.sublime-settings manually in my Package User folder

**Comment by facelessuser** [comment]
Okay, so this doesn't seem to be a bug at all. In order for me to add support for a new syntax package, I will need to be provided with example source code as I don't code in less or scss.  I will close this issue for now, but feel free to either provide source examples here that I can test with, or please create a pull request.

**Comment by facelessuser** [comment]
Oh, I also added ColorHelper in `Preferences -> Packages Settings`.  That will be in the next release.

**Comment by zackdouglas** [comment]
Greetings, sorry for my [ambiguity](https://github.com/facelessuser/ColorHelper/issues/16#issuecomment-157822652)! I just installed this yesterday, 10 minutes before I reported the comment. I'm not using Jinja myself, at all.

I just tested this again with a straight-CSS file, and it works great! I was indeed using the SCSS package.

Please forgive my ignorance, but, how would I manually add the SCSS scope? (Or, I'll just await the release with Preferences.)

Cheers!

**Comment by facelessuser** [comment]
I don't use scss, so if you provide me a good scss example, I can figure out the scopes and let you know what to add until I get around to another release.

**Comment by facelessuser** [comment]
Okay, I added scopes for SCSS package.  I think in the future I will make new scopes pull request only.  It will make it easier on me by placing the onus on those that desire support for some shiny new syntax package that isn't already supported.  I am hoping though that the current support will now cover the all major packages.  I guess if it gets too bad, I can always generalize the scanning more (though I was trying to avoid scanning whole files).  I might have a release out tonight with all the new stuff.

**Comment by facelessuser** [comment]
New version was released.  When it updates, SCSS should work.

**Comment by zackdouglas** [comment]
Verified! Thanks, so much!

**Comment by facelessuser** [comment]
Still some tweaking going on: see https://github.com/facelessuser/ColorHelper/issues/20#issuecomment-158328632.  But each iteration, I get it closer to what we want :smile:.  I may have to overhaul the scope system to give a more flexible way to control all of this per file type etc.  We'll just see how things play out.
