### ISSUE TITLE
Support more blend modes

### ISSUE THREAD

**Issue by AmjadHD** [facelessuser/ColorHelper#162]
## Description

When applying a tint to a texture ST performs a channel-wise multiplication. Sometimes when I'm developing a theme, and creating a somewhat complex texture (contains more than one color) I need to know what colors I should choose to get the correct colors when the tint is applied.
It would be handy if ColorHelper supported more [blend modes](https://en.wikipedia.org/wiki/Blend_modes) than only addition. 
The syntax can look like:
`Color((percent)? + Color(percent)? (!blendmode)? (@colorspace)?)?`

## Support Info

- ST ver.: 3211
- Platform: windows
- Arch: x64
- Plugin ver.: 3.0.0-beta.01
- Install via PC: False
- mdpopups ver.: 3.7.5
- markdown ver.: 3.1.1
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

**Comment by facelessuser** [comment]
It is something we can consider, but we'll see. The current underlying library utilizes the blending methods employed by the CSS color spec (mainly `color-mix()`). That's not saying we can't add more, but not all blend modes will necessarily work for cylindrical color spaces and non-cylindrical.

So, it is something we can consider, but I won't make any guarantees right now.

**Comment by facelessuser** [comment]
@gir-bot remove S: triage
@gir-bot add T: feature, P: maybe

**Comment by facelessuser** [comment]
So, I've actually spent some time on this, and I now have the `coloraide` library (at least locally), handling all the various blending modes covered in the HTML compositing specification: https://www.w3.org/TR/compositing/#blending.

<img width="832" alt="Screen Shot 2021-04-04 at 4 27 09 PM" src="https://user-images.githubusercontent.com/1055125/113523083-faae6980-9562-11eb-8345-8651ad1fa2c5.png">

As mentioned, this follows the HTML spec. Nor sure if it follows PhotoShop or not, so there may be some subtle differences. I've compared the results to Firefox's implementation of `mix-blend-mode` and it seems to match.

Now, once I get it cleaned up and tested, I would have to think about how to expose it in ColorHelper. Maybe a specific Blend tool 🤷🏻.

**Comment by facelessuser** [comment]
Hmm, pretty sure this is to spec, and it matches Firefox, but it appears Firefox implements things differently than Chrome and Safari... 🤔

**Comment by facelessuser** [comment]
I was going mad trying to figure out why Chrome **and** Safari, were both different in the exact same way, and Firefox seemed to match my implementation that was produced from the spec.

Turns out, everyone is correct. Chrome, Safari, and Firefox (us as well) are all doing it exactly right. So why the difference?

Well, it all boils down to color spaces. Apple is shipping monitors that can handle colors in the gamut of `display-p3`. So, Safari is looking towards the future and blending in `display-p3` and so is Chrome.

Firefox is still blending by default in `srgb`. So, we can match Chrome and Safari simply by blending in `display-p3` (circles are blended by the browser via CSS and the square colors are ours):

<img width="726" alt="Screen Shot 2021-04-04 at 8 45 27 PM" src="https://user-images.githubusercontent.com/1055125/113531990-82a66a80-9587-11eb-8c6d-0a9336ad4df3.png">

And we can match Firefox by blending in `srgb`:

<img width="716" alt="Screen Shot 2021-04-04 at 8 46 00 PM" src="https://user-images.githubusercontent.com/1055125/113532009-92be4a00-9587-11eb-958a-7413eae1e207.png">

So, there is nothing wrong with our algorithm or theirs as they are all the same, just the inputs are different.

I feel less crazy now and much more confident with our algorithm now.

**Comment by facelessuser** [comment]
I should clarify. The discrepancy seems to be due to color management. you have to enable color management in Firefox to get the same results as Chrome and Firefox. If I had a different display, color management would probably cause things to look different.

**Comment by facelessuser** [comment]
ColorHelper now has a version of coloraide that supports blend modes, it just doesn't expose them yet. I'd have to figure out what that will look like, I may play with creating a separate blend tool to play with blending. But coloraide now supports a bunch of blend modes now, so the hard part is done.

https://facelessuser.github.io/coloraide/compositing/#blend-modes.

I should note that blend modes are not the same thing as our interpolation that we use for mixing. I don't think it is going to be built in the same way the mixing/interpolation is. It's more a compositing thing than a color mixing thing.

**Comment by AmjadHD** [comment]
Great Job ! That should be helpful.

**Comment by facelessuser** [comment]
You can play around with them in the live demo: https://facelessuser.github.io/coloraide/playground/.

Something like this:

```py
Color('#07c7ed').compose('#fc3d99', blend='multiply')
```

We'll see when I get a chance to expose them. Just got done fixing some conversion issues. The CSS spec had some conflicts in conversion through XYZ that affected Lab conversions and such. Just got finished debugging and fixing that.

**Comment by facelessuser** [comment]
This is the last planned task for the next release. We'll probably keep it simple.

- You will be able to blend two colors.
- Default mode is "normal" but you can specify different modes.
- The environment will be treated as isolated over a white background, so if your backdrop color is transparent, it will be blended in "normal" mode over white, and the source color will be laid on top.
- If you want the source to have less of a say in the overall color, you can control it by adjusting transparency.
- This of course assuming "source over" compositing. The default used in browsers and such.

I'm open to suggestions, but this is my plan for the first cut.

**Comment by facelessuser** [comment]
Working blend mode command

<img width="627" alt="Screen Shot 2021-04-20 at 7 52 11 PM" src="https://user-images.githubusercontent.com/1055125/115485438-f72d0a80-a211-11eb-92fd-e14da3a465f0.png">
