### ISSUE TITLE
With CH 3.0.2 enabled, search result highlights immediately disappear

### ISSUE THREAD

**Issue by luckman212** [facelessuser/ColorHelper#165]
## Description

With CH3.0beta02 installed, when I use ⌘F and ⌘G to find and iterate over search results, the normal yellow highlight background only briefly flickers and then disappears. Best shown with a video:

https://user-images.githubusercontent.com/1992842/109042975-cf507900-769e-11eb-8908-114bca8eb96d.mp4

Here's the same thing, but with the CH package disabled:

https://user-images.githubusercontent.com/1992842/109043006-d8d9e100-769e-11eb-94dc-6c49215eca3a.mp4

Not sure what could be causing this, but it makes it harder to see the results for sure. Thank you.

## Support Info
```
- ST ver.: 3211
- Platform: osx
- Arch: x64
- Plugin ver.: 3.0.0-beta.02
- Install via PC: True
- coloraide ver: 0.1.6
- mdpopups ver.: 3.7.5
- markdown ver.: 3.1.1
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1
```

**Comment by facelessuser** [comment]
Ugh. This may be a Sublime issue, related to phantom insertions, but I'm not sure. I'll have to investigate. It's definitely not ideal, but I'll have to dig a little deeper to see what the cause is.

While I can reproduce it, it doesn't always happen, so I'm already thinking it isn't something I'm fundamentally doing wrong, or it would always break.

![find](https://user-images.githubusercontent.com/1055125/109044370-9230ba80-768f-11eb-9f74-7f3b057d31b6.gif)

**Comment by facelessuser** [comment]
@luckman212, it is related to the more aggressive event looping from your last request. Increasing the time back from 0.25 to 0.5 makes it stop. Probably not what you want to hear though 🙃 .

**Comment by luckman212** [comment]
Hah :) I was afraid of that!

I was thinking of giving ST4 a try to see if it behaved any differently. Are you running ST4 or ST3 on your dev setup?

**Comment by facelessuser** [comment]
> I was thinking of giving ST4 a try to see if it behaved any differently. Are you running ST4 or ST3 on your dev setup?

ST4

**Comment by facelessuser** [comment]
We can probably pick a slightly less aggressive value but still try and keep some of the snappiness. I think we are just running into a race condition with certain Sublime events. We probably need to back off a little to give Sublime a chance to do its thing.

@gir-bot remove S: triage
@gir-bot add T: bug, P: low

**Comment by facelessuser** [comment]
I think we'll try and bump it from 0.25 to .30. It seems to give me no issues, so we'll try that for now. I'll double check on my older system as well. Worst case, maybe we'll bump it to .35, but I think that should be fine.

**Comment by luckman212** [comment]
Thanks for this. I'll keep an eye on it. Will switch to ST4 soon, probably in March.

**Comment by facelessuser** [comment]
This seems it may not be related to timing. Recently, it started again, and increasing and decreasing the time made no difference. This will require more investigation.

**Comment by facelessuser** [comment]
Okay, I think this may be caused by something else. Sublime will revert a find selection to a normal selection if/when the view loses focus. It is possible that ColorHelper causes the view to lose focus somehow, and that is probably the cause. What in ColorHelper makes the view lose focus? That is the real question.

We never have to refocus the view, so I'm not sure what is causing the focus loss. I imagine there is some command within Sublime that causes focus loss. I'll have to dig a lot deeper to try and identify the culprit, especially since sometimes the highlight isn't lost, so it can be difficult to pin down. The real thing we are attempting currently is identifying whether this is an issue with what we are doing or some side-affect of Sublime doing some wrong.

**Comment by facelessuser** [comment]
I think I know what the issue is. In ColorHelper, we use a Sublime TextCommand. I think these commands put the view in an edit mode, which, when highlighting find results, will break the find highlighting.

We do this so that we can use the command, where one is created for each view, to track the current previews we've created as this information is not easily accessible, and is more expensive to save in the view's settings. It is also useful as Sublime will automatically clean up these commands for new views and create new ones for new views.

I suspect if we moved to a WindowCommand, we could do the same thing, but we'd have to manage all the creation and clearing of cached previews. I also suspect that WindowCommands would not interfere with find highlights.

**Comment by facelessuser** [comment]
I think #167 will have the actual fix. I've tested it out, and I'm not running into the find issue. It appears that running a TextCommand while a find highlight is active, will cause the view to go into edit mode, which will cause the find highlight to turn into a normal selection. There seems to be a little bit of timing of when the find highlight is applied and when the TextCommand is run, so sometimes the highlight breaks and sometimes it does not.

WindowCommands do not have this issue, so we just have to track per view info in the WindowCommand and manage it. It seems to work, so I'm thinking this will be the solution. I'll do some more testing though.

**Comment by luckman212** [comment]
Wow that's great. I installed ST4 (4098) today and am kicking the tires.

**Comment by luckman212** [comment]
Just wanted to say, this fix is working great! Thank you @facelessuser

**Comment by facelessuser** [comment]
No problem. Glad it's working for you. I'm surprised I didn't notice it until you pointed it out 😅.
