### ISSUE TITLE
Question: ColorHelper in Sublime "*.tmTheme" files

### ISSUE THREAD

**Issue by Fabianred** [facelessuser/ColorHelper#21]
Is it possible to use this extension with sublime color scheme files *.tmTheme?
How can I do that?

**Comment by facelessuser** [comment]
1. Right now everything is done by specific scopes and I can't currently restrict it to certain extensions.  I probably need to think about reworking the current system to take input such as file extension, syntax language used, and scope.  But currently that isn't possible.

2. Also, it won't currently work on tmTheme alpha colors: #RRGGBBAA.  I can probably add #RRGGBBAA support in the future (I think it is a proposed format for CSS4?), but I would need a system that cold exclude it in certain files...so this references back to statement (1.) .

3. Thinks like tmTheme languages use the XML langauge, so they don't really have scopes where only colors are applied, so this will falsely cause popups in non color tags, but that may be worth living with.

Good news is that you can always manually call the colorpicker, color info, or color palette tooltip form anywhere, and it will even pick up colors in not enabled files.

This is the first time the plugin is being exposed to such a large audience, so it is also the first time I am finally getting good feedback.  So things may get overhauled in the future to fit the demands of the users.

**Comment by facelessuser** [comment]
tmTheme support coming soon!

![screenshot 2015-11-29 20 06 20](https://cloud.githubusercontent.com/assets/1055125/11462691/c96d8726-96d4-11e5-8b6d-07d742f7dfe4.png)

**Comment by Fabianred** [comment]
Great!
Will it automatically launch tooltip in *.tmTheme files or only via command in "CTRL+SHIFT+P" menu? 
How about sets for hotkeys and mouse menu context in pre listed files extensions?

**Comment by facelessuser** [comment]
> Will it automatically launch tooltip in *.tmTheme files or only via command in "CTRL+SHIFT+P" menu? 

Auto.

> How about sets for hotkeys and mouse menu context in pre listed files extensions?

I never provide hotkeys; I let users set that up as I don't want to conflict with  a user's custom hotkeys.  As for context menus, maybe, I just haven't added any yet. Maybe I can optionally provide context menus.  If I did, they would work on files that are set up to auto-detect colors.  For instance, `tmTheme` files would auto-detect because I have set them up to auto-detect; therefore, if I added context menus, they would appear in `tmTheme` files:

```js
        {
            "syntax_files": [],
            "base_scope": ["text.xml"],
            "scan_scopes": ["text.xml -meta.tag.xml -comment -string"],
            "allowed_colors": ["hex", "hexa"],
            "extensions": [".tmTheme"],
            "use_argb": false
        }
```

By the definition above, if the file extension on disk is `.tmTheme` and the base scope of the file is `text.xml`, it will detect colors (and in your case show context menus if I add them).  I could probably also provide an option to always show context menus even in files where auto-detect is not supported.  This would be user configurable.

**Comment by facelessuser** [comment]
Context menu will be in the next release as well.  Palette and color picker will be enabled in any file.  Color info will only be enabled when the cursor is on a recognized color, but should work in any file.  You do not need any kind of configuration to get these to work, though if you want hex AARRGGBB support instead of RRGGBBAA, then you would need configuration for that file type.  Hotkeys will be left up to the user.

**Comment by facelessuser** [comment]
This will be in the next release.
