### ISSUE TITLE
Version 6.0.0 fails to show previews/swatches

### ISSUE THREAD

**Issue by maegul** [facelessuser/ColorHelper#227]
Please read and fill out this template by replacing the instructions with appropriate information.  If the template is not followed, the issue will be marked `Invalid` and closed.

Before submitting an issue search past issues and read the area of the [documentation](http://facelessuser.github.io/ColorHelper/) related to your specific question, issue, or request.

---

## Description

... what is the issue / request ?

No previews/swatches appear when they were appearing just fine in the previous version (5.0.1).  No other changes have been made to Sublime other than the update to 6.0.0.

I have no nor used to have any user settings for colorhelper.

Syntaxes checked: sublime-color-scheme and CSS.

> Vague issues/requests will be marked with `Insufficient Details` for about a week.  If not corrected, they will be marked `Stale` for about a week and then closed.

> For feature requests or proposals:

> - Clearly define in as much detail as possible how you imagine the feature to work.
> - Examples are also appreciated.

> For bugs and support questions:

> - Describe the bug/question in as much detail as possible to make it clear what is wrong or what you do not > understand.
> - Provide errors from console (if available).
> - Pictures or screencasts can also be used to clarify what the issue is or what the question is.
> - Provide links to 3rd party syntax highlighting package you are using if applicable.

## Support Info

- ST ver.: 4131
- Platform: osx
- Arch: x64
- Plugin ver.: 6.0.0
- Install via PC: True
- mdpopups ver.: 4.2.2

> Run the following command from the menu: `Preferences->Package Settings->ColorHelper->Support Info`.  Post the result here.

## Steps to Reproduce Issue

1. Upgrade to 6.0.0
2. Open file where color previews used to appear
3. Check for ColorHelper functionality, including appearance of previews

> Provide steps to reproduce the issue. Pictures are fine, but also provide code/text I can copy and paste in order to reproduce. Omit for feature requests and feature proposals.

**Comment by facelessuser** [comment]
Did you restart ST after upgrade?

**Comment by facelessuser** [comment]
Also, it may not apply to you, but the upgrade notice mentions:

> - If you tweaked the new`add_to_default_spaces`, please compare against
>   the default list as some plugins were renamed and user settings may
>   need to get updated. Color space plugins that do not properly load
>   should show log entries in the console.

**Comment by webzone-vn** [comment]
Not working after upgrade to 6.0.0

**Comment by maegul** [comment]
@facelessuser :
* Yep, restarted, multiple times
* Never touched `add_to_default_spaces`.

**Comment by facelessuser** [comment]
Any console errors?

I'll have to install in a portable Sublime as things are currently working local, but maybe a clean install will reveal something.

**Comment by facelessuser** [comment]
Okay, I've found some issues. ColorHelper always embeds the latest and greatest coloraide, but I do offer coloraide as a separate Sublime dependency that may not be on the bleeding edge...unfortunately, since I have both installed for testing, some issues were not caught.

Apparently, I accidentally had some absolute references in coloraide. This was unintentional, and all references should be relative. So there are some absolute references reaching out to a non-vendored coloraide that does not exist on your system. I'm working to fix the issues now.

**Comment by facelessuser** [comment]
It was a single reference in a new natural B-spline interpolation method 🤦🏻 . I had originally implemented the interpolation method as an external plugin, and when making it official and placing it in the code base, I forgot to change the reference to a relative import. Since we vender the library in ColorHelper, we have to have everything relative. I'll have a fix out in just a few.

`from coloraide import algebra as alg` needs to be `from .. import algebra as alg`

**Comment by facelessuser** [comment]
I have a release tagged. It should be available in Package Control within an hour or 2. Do let me know if you run into other issues. This should be the last major upgrade to the underlying coloraide library for quite some time as the library is now considered stable.

**Comment by facelessuser** [comment]
Closing as a fix has been released via https://github.com/facelessuser/ColorHelper/commit/5aaa23a8c98ea453c372cdf472ce6a299a705225

**Comment by maegul** [comment]
@facelessuser Looks all good on my end.  Nice work on the quick turn around ... hope it's all stable now.

And, in general, thanks for all the work on all the Sublime plugins you do ... awesome stuff ... don't know how you do it!

**Comment by facelessuser** [comment]
No problem

> don't know how you do it!

An unhealthy obsession 🙃. Glad you find some of this stuff useful.
