### ISSUE TITLE
file color index complete instead of made n replacement

### ISSUE THREAD

**Issue by ildarkhasanshin** [facelessuser/ColorHelper#34]
replace text, and the text file color index complete... appears in the status bar in place of the text made n replacement - if temporarily disable a plug, it can be seen

**Comment by facelessuser** [comment]
On save, ColorHelper will index the colors and post a notice in the status bar.  If you are doing a basic status, it overwrites the last status message.  I can't really control that.  It's just the way Sublime works.

Do you want the status for ColorHelper removed entirely?  I guess I could do that and create a setting to enable/disable it.

**Comment by ildarkhasanshin** [comment]
> Do you want the status for ColorHelper removed entirely? I guess I could do that and create a setting to enable/disable it.
yes

**Comment by facelessuser** [comment]
Okay, I think I can at least do that.

**Comment by ildarkhasanshin** [comment]
very tired of the constant phrase in the status line( would need an option as soon as possible

**Comment by facelessuser** [comment]
> very tired of the constant phrase in the status line( would need an option as soon as possible

This is a free plugin.  I don't get paid to maintain this.  So I usually get around to addressing issues when I have free time and I feel like working on the plugin. Since this is also not a critical bug, this will remain a low priority issue.  If the plugin is unusable to you because of this, you are free to uninstall or issue a pull request.

**Comment by ildarkhasanshin** [comment]
good!
