### ISSUE TITLE
Use phantoms to show the color beside its definition

### ISSUE THREAD

**Issue by aziz** [facelessuser/ColorHelper#36]
This is what a lot of people asked for and now it should be possible. Yay!

**Comment by facelessuser** [comment]
This is indeed interested.  Originally I wasn't interested in showing colors, but with the introduction of phantoms, I am actually intrigued and will probably give this a try when I have some free time to devote to it.

**Comment by gwenzek** [comment]
The following plugin will show colors in format #FFFFFF found in YAML files with phantoms.
Quite useful for editing your YAML-thTheme

```
import sublime
import sublime_plugin

class ViewCalculator(sublime_plugin.ViewEventListener):
    def __init__(self, view):
        self.view = view
        self.phantom_set = sublime.PhantomSet(view)
        self.timeout_scheduled = False
        self.needs_update = False

        self.update_phantoms()

    @classmethod
    def is_applicable(cls, settings):
        syntax = settings.get('syntax')
        return syntax == 'Packages/YAML/YAML.sublime-syntax'

    def update_phantoms(self):
        phantoms = []

        # Don't do any calculations on 1MB or larger files
        if self.view.size() < 2**20:
            candidates = self.view.find_all("'?#[a-fA-F0-9]{6,8}'?")

            for r in candidates:
                color = self.view.substr(r).strip("'")
                phantoms.append(sublime.Phantom(
                    sublime.Region(r.b),
                    '<span style="color:%s">■<span>' % color,
                    sublime.LAYOUT_INLINE
                ))

        self.phantom_set.update(phantoms)

    def handle_timeout(self):
        self.timeout_scheduled = False
        if self.needs_update:
            self.needs_update = False
            self.update_phantoms()

    def on_modified(self):
        # Call update_phantoms(), but not any more than 10 times a second
        if self.timeout_scheduled:
            self.needs_update = True
        else:
            sublime.set_timeout(lambda: self.handle_timeout(), 100)
            self.update_phantoms()
```

**Comment by facelessuser** [comment]
- This doesn't show color transparency , which I want if I'm going to do this.
- I'm also not sure if I want scan the whole file on every `on_modified` event even with a 1MB file limit.
- This also doesn't handle rgb(a) and other color formats.

If it works for you, that is great.  I am just imagining something a bit different.

I think what I would like to do is only scan the visible portion of the view.  So when you scroll, it could update the visible colors, and if you modify, it would update when not busy processing keystrokes.  I imagine we will wait for a specific amount of time of idleness before executing on scroll/modify events.

So in general, there will probably be a running thread that will periodically check if the view has scrolled.  Also, we can managed a flag for modify events, and if there has been X amount of time of idle modifications, then the thread will handle the modify request.

This is all just what I think I want right now.  I have various plugins already that employ similar thing, but I just haven't had time to sit down and play with this yet and see how well it would work in the ColorHelper environment.

**Comment by gwenzek** [comment]
This wasn't mean as a PR rather as a proof of concept, and a quick hack for waiting something smarter 😃

**Comment by facelessuser** [comment]
No problem.  I just wasn't sure.

**Comment by facelessuser** [comment]
So, I played around with this tonight.  What I actually have going is a system that loads the colors that scroll into view.  When they scroll out of view, they persist.  So essentially, we load up colors on demand as they are viewed.  When an editing event occurs, we trash all the colors in the view and start over.

![screenshot 2016-07-19 23 32 13](https://cloud.githubusercontent.com/assets/1055125/16976097/8a46f7a2-4e09-11e6-8282-20b307e61478.png)

I still have a lot to iron out, and I don't know when I'll be done as I am not really rushing to get this done, but it looks promising.

**Comment by facelessuser** [comment]
You guys are welcome to try out the [experimental branch](https://github.com/facelessuser/ColorHelper/tree/experimental_preview) and give feedback.  Remember it is very much alpha quality.  It doesn't scale the images for high res screens yet (or even have an option to manually force them to scale).

The current implementation basically checks for the viewable region changes to recognize scrolling.  When you scroll to a new place, you should see images being generated.  The slowest part of the process is Sublime inserting the phantoms; for this reason, we use a set_timeout_async to let Sublime do this on a separate thread to ensure we have good response.    Also, because we are doing this asynchronously, when we edit the file, we don't even try to predict where to insert new phantoms, we just scrap the phantoms and start over when there is a sufficient idle moment to start regenerating.  Once a phantom is inserted, we don't regenerate it unless there is an edit event or a save event.

Due to the time it takes to do all the work, sometimes you will only have part of the colors generate d in a viewable region, just scroll a little and you will see the rest regenerate.  This is probably due to the event starting as you were scrolling at an earlier point and not yet done.  We don't allow new scroll refreshes until the current is done, and after the refresh is done, we then lock the last viewable region to the result after inserting the phantoms as phantoms can change the viewable region by changing line height.  Maybe I scan past the viewable region more in the future to ensure we have a better refresh.

The code is very rough, but seems to work pretty good, but I haven't extensively tested it, and obviously there will be improvements coming down the pipe as I have more time to play with this.  But if you are brave enough to try this, feedback or notes on quirks will help development move faster on this.

**Comment by facelessuser** [comment]
Images should now scale to line_height and if the line_height changes (due to font size changing), they will be redrawn.  This will probably require a retina flag for OSX, but I will have to test that later.  Using the line height as a gauge turned out pretty better than I thought as it seems to give an accurate px value which doesn't seem to require me to know the font scale, I may use that to detect font sizes in mdpopups if it works out well.  I don't know if this will work well on OSX retina, but I will take a look at that tonight.

**Comment by aziz** [comment]
here are my two cents:

- [ ] Clicking on the preview box should open the ColorHelper picker panel or colorPicker
- [ ] Is is possible to vertically align the box with the line content?
- [ ] Is there a way to get rid of the border around the box? you don't have it in your screenshot
<img width="359" alt="screen shot 2016-07-20 at 7 48 56 pm" src="https://cloud.githubusercontent.com/assets/3202/16996895/7af66f1c-4eb3-11e6-9141-2c41c251a479.png">

**Comment by facelessuser** [comment]
> Clicking on the preview box should open the ColorHelper picker panel or colorPicker

We're not there yet :smile:, but I've thought about something like that.

> Is is possible to vertically align the box with the line content?

Are you using the most recent commit? I'm not having your issues.  The first commit I posted, I don't size the image to the line, so you can get an image bigger than the line.  But the most recent commit (assuming you are using the default mdpopups CSS) sizes the image to fit on the line.  I am not having your issue:

![screenshot - 7_20_2016 12_20_40 pm](https://cloud.githubusercontent.com/assets/1055125/16997892/985600ac-4e74-11e6-82f5-d32649ea5058.png)

If you are using the most recent commit, then maybe it is a combination of things like font being used? I don't know, I would need more info.

>  Is there a way to get rid of the border around the box? you don't have it in your screenshot 

Yup.  Mdpopups doesn't currently use a different CSS for phantoms vs popups.  Locally in my user folder I have overridden the border to be the same as the background by using the `is_popup` flag.  Just create a file called `User/mdpopups.css` and copy the code below into it (then restart sublime).  I will probably do this in the default mdpopups css in the future.

```css
/*Style with current theme.*/
{% if var.is_popup %}
{% if var.is_light %}
html{ {{'.background'|css('background-color')|brightness(0.9)}} }
{% else %}
html{ {{'.background'|css('background-color')|brightness(1.1)}} }
{% endif %}
{% else %}
html{ {{'.background'|css('background-color')}} }
{% endif %}
h1, h2, h3, h4, h5, h6 { {{'.string'|css}} }
blockquote { {{'.comment'|css}} }
a { {{'.support.function'|css('color')}} }
hr { {{'.comment'|css('color')|background}} }
body { {{'.foreground'|css}}{{'.background'|css}} }
.admonition { {{ '.support.function'|css('color')|background|fade(0.8) }} }
.hint, .tip { {{ '.keyword'|css('color')|background|fade(0.8) }} }
.danger { {{ '.entity.name.tag'|css('color')|background|fade(0.8) }} }
.important, .attention { {{ '.string'|css('color')|background|fade(0.8) }} }
.caution { {{ '.constant.numeric'|css('color')|background|fade(0.8) }} }
.note { {{ '.variable.language'|css('color')|background|fade(0.8) }} }
{% if var.use_pygments %}
{% if var.is_light %}
{{'default'|pygments}}
{% else %}
{{'native'|pygments}}
{% endif %}
{% else %}
{% if var.is_light %}
.highlight, .inline-highlight { {{'.background'|css|brightness(0.9)}} }
{% else %}
.highlight, .inline-highlight { {{'.background'|css|brightness(1.1)}} }
{% endif %}
{% endif %}
```

**Comment by facelessuser** [comment]
I added clicking the colorbox in the most recent commit.

**Comment by facelessuser** [comment]
Margins around body tags in phantoms will be removed in the next mdpopups release.

**Comment by facelessuser** [comment]
With new phantom additions, I plan on removing the popup when the color text is clicked and require that you click the color preview instead.  Do you guys have objections to that?  Or other ideas?

**Comment by aziz** [comment]
I don't have any problem with it. 
but some people probably want to disable phantom previews and for those it should be triggered using the color text.

**Comment by facelessuser** [comment]
> but some people probably want to disable phantom previews and for those it should be triggered using the color text.

Yes, the previews will be configurable.  I intend to remove them completely, but I thought about it for the previews at least.  I think initially I will leave it as is for the next release and think about whether I prefer hover or click etc.

In general, I am happy with the current state.   I think I will focus on adding the setting  toggle, and maybe address the responsiveness to try and eliminate the occasional color(s) that doesn't get the color preview due to missing the scroll event.

**Comment by facelessuser** [comment]
Okay, I think I've made my last commit on this.  Please let me know if the most recent change has any issues.  I am calling this a release candidate.

**Comment by aziz** [comment]
- The border in my previous screenshot is gone when I used the your custom `User/mdpopups.css` file
- with current setup It causes a vertical jump which is annoying. I think there might be a bug in calculating the image size or in Sublime phantom API. 
![jul-23-2016 20-48-57](https://cloud.githubusercontent.com/assets/3202/17079660/9ac65ff8-5117-11e6-981b-973e92f9b849.gif)

I managed to fixed by adding extra padding on the top and bottom of my lines (changed from 1 to 2)
```
	"line_padding_bottom": 2,
	"line_padding_top": 2,
```

here is my font related settings if you want to replicate
```
"font_face": "source code pro",
"font_size": 18,
"caret_extra_top": 1,
"caret_extra_bottom": 1,
"caret_extra_width": 1,
```

**Comment by aziz** [comment]
The positioning of the box is still not perfectly vertically centered which is more visible on my retina screen: 
<img src="https://cloud.githubusercontent.com/assets/3202/17079780/82aeb67e-511a-11e6-932f-3b6b802a1266.png">

**Comment by facelessuser** [comment]
What font do you use.  I can't replicate this.

**Comment by facelessuser** [comment]
I also find it odd that adding padding helps as I literally use this to calculate size:

```
        padding = int(self.view.settings().get('line_padding_top', 0))
        padding += int(self.view.settings().get('line_padding_bottom', 0))
        box_height = int(self.view.line_height()) - padding - 6
```

So whatever padding you add, get's subtracted out.

I feel like Sublime is a little inaccurate here.  I noticed on mine that the images are perfectly centered **except** when line height gets really small; then the images get smaller than they should be.  So I feel like Sublime reports odd things in certain situations.

So what I'll do is expose the fudge value `6`.  That is basically subtracting any padding.  But if I expose it, you can pick something that works for you.

**Comment by facelessuser** [comment]
You know, before I expose some weird constant, let me force no padding in the HTML and see if that helps.

**Comment by facelessuser** [comment]
Okay, I think I have a fix.

Please upgrade to latest, but also run `Satisfy Dependencies` to get latest `mdpopups`.

I've decided that phantoms should not have padding added to them by default.  That should be left up to plugins to decide (using a wrapper div with classes to namespace it).  Since stuff is getting inserted possibly inline, formatting gets in the way.  Anyways, ColorHelper no longer fudges anything.  As the default padding was done with `em` that explains why it would scale funny in some scenarios.  With that gone, images should fill the entire line height properly.

Please report back when you get a chance to try it.

**Comment by aziz** [comment]
Now I need to bump the padding to 4.
![linepadding0](https://cloud.githubusercontent.com/assets/3202/17080267/1cad9b7e-5129-11e6-871d-fe17f5d94dd4.gif)
![linepadding1](https://cloud.githubusercontent.com/assets/3202/17080268/1df94a00-5129-11e6-9ba7-7dec694bdf50.gif)
![linepadding4](https://cloud.githubusercontent.com/assets/3202/17080271/21f726f4-5129-11e6-85c8-553df032fd08.gif)

**Comment by facelessuser** [comment]
Lol. Okay, I tried it on my 4K computer and I see it now too.  I'm going to expose a setting to tweak this.  Sublime sucks at telling me what I need to know.  I can't calculate this reliably.

**Comment by facelessuser** [comment]
Update to latest commit and set `inline_preview_offset` to a negative number to shrink image size by the specified px.  This is the best I can do.  Hopefully that will fix it for you.

```js
    // Adjust the size of inline image previews by the offset given.
    // Please use either a positive or negative number.
    "inline_preview_offset": 0,
```

**Comment by aziz** [comment]
Worked like a charm. Thanks 👍

**Comment by facelessuser** [comment]
Cool, I'm going to call this done.

**Comment by facelessuser** [comment]
Released in 2.0.0.  Thanks for your help in testing @aziz.

**Comment by aziz** [comment]
How about updating the Screenshots on Readme with an image of this  new feature?

**Comment by facelessuser** [comment]
Yeah.  I do plan to do that. I was just tried of fooling with it and released it.  I'll revisit the docs in a little bit once I take a break.
