### ISSUE TITLE
Font size is too small

### ISSUE THREAD

**Issue by oivva** [facelessuser/ColorHelper#39]
I use Boxy Yesterday, but the same story with the default theme.

![shot_160718_084818](https://cloud.githubusercontent.com/assets/9801624/16906704/ce28e99e-4cc4-11e6-956d-15741a90fa0c.png)

Sublime Text 3114, 3118
Windows 7
DPI scale: 1

**Comment by facelessuser** [comment]
Yup, that was not done on purpose.

**Comment by facelessuser** [comment]
st3-1.4.2 should clear this up.  Thanks for letting me know.

**Comment by digeomel** [comment]
Is this already committed in the latest version? I get it as well :disappointed:

**Comment by facelessuser** [comment]
There are a couple of factors involved.  Post your `Preferences->Package Settings->ColorHelper->Support Info` output here.

**Comment by digeomel** [comment]
- ST ver.:        3083
- Platform:       linux
- Arch:           x64
- Plugin ver.:    2.0.3
- Install via PC: True
- mdpopups ver.:  1.8.0
- markdown ver.:  2.6.6
- pygments ver.:  2.1a0
- jinja2 ver.:    2.8

**Comment by facelessuser** [comment]
Is this a 4K screen you are seeing this on?

**Comment by facelessuser** [comment]
Is it all text or just some?

**Comment by digeomel** [comment]
It's a desktop, 1920x1200 resolution monitor with RHEL 7 and Cinnamon.
Here's a screenshot:

![screenshot from 2016-07-29 17-00-42](https://cloud.githubusercontent.com/assets/3295889/17252774/30ed9d4e-55ae-11e6-9ce5-51968270f0ac.png)

**Comment by facelessuser** [comment]
Looks like a general scaling issue.  In your `Preference.sublime-settings` file you can specify the font scale with the following mdpopups setting: http://facelessuser.github.io/sublime-markdown-popups/usage/#mdpopupsfont_scale.

The better solution is to switch to Sublime 3119 which now uses relative em units which mdpopups will use by default.  In that case you won't need a font scale setting.  This will scale all font to match what's in your view perfectly with no hacks (assuming you don't override the CSS with something non-relative).  Also you get nice inline colors previews 😉 .

Anyways, the choice is up to you.

**Comment by digeomel** [comment]
Tried the first option, set the scaling factor to 1.5 and I'm good, thanks :+1:

**Comment by darkguy2008** [comment]
I'm still having this issue with ST 3126, I tried to add the 'mdpopups.font_scale': 0 flag to 1, 2, etc. without success in my Sublime Text settings file and in my ColorHelper settings file: 

![image](https://cloud.githubusercontent.com/assets/6304136/25786510/c782e0b0-3353-11e7-8884-66f396899747.png)
 
Any ideas?

**Comment by facelessuser** [comment]
You are referring to the font size?  It seems to match your view font like it should.  Most of my plugins on later versions no longer use `mdpopups`' `relativesize` which relied on `mdpopups.font_scale`.  This is because Sublime now has `rem` sizes which is a much better relative font size implementation. MdPopups will drop its hacky `font_scale` in the next major release due in June.

So I assume your real issue is not that the font size is too small, but the font size of some items are too small to your liking (like the menu items).  Some of the fonts are a little smaller because I apply the class `.small` to the them and make them smaller.  In the future I can possibly make them a little bigger, but I purposely wanted certain elements a little smaller, but maybe they are too small.

In your `Users/mdpopup.css` file you can probably make the size a little bigger by doing something like shown below.  Keep in mind that 1rem is the base size, and currently small is `0.7rem`.

```css
.color-helper .small { font-size: 0.8rem; } /* or what ever value you like */
```

You didn't list what version of mdpopups is on your machine, but run `Package Control: Satisfy Dependencies` to make sure you have the latest as Package Control doesn't always use the latest.

**Comment by darkguy2008** [comment]
Hello! Thanks for your prompt answer! Yes, I've noticed it tries to match my view font's size, failing miserably due to the .small class. In my opinion, this should be a setting in a configuration file instead, or remove the .small, whichever works, but when you use the smallest text size it screws up that bad.

Well, the fonts are small, but it's not that I like them that small, it's because they're so small I can *hardly* see the text and even click on the options, it's too hard to read, it ends up being like a font size 4 or 6pt on Windows, which is unreadable. Another option would be to just set a minimum text size to avoid this problem, or just make it configurable anyways, that's why we have the settings for, right?

I've run the command you have requested and it says that all the dependencies have been satisfied. I have no idea about the mdpopups installed, I'm on Windows and I haven't installed anything related to that. How can I provide that info to you? I don't really know anything about plugin development, I just want to help you fix this issue because it's still happening :P . I'll try that .css modification and see if that works... as a workaround, I have to increase font size, change color and revert back, it's not ideal, but it works :)

**Comment by facelessuser** [comment]
> Yes, I've noticed it tries to match my view font's size, failing miserably due to the .small class.

It's not failing, it is doing what it is supposed to.  Those elements assigned `.small` are supposed to be smaller than the view's font. Everything else is sized to the view's font.

Yes **some** of the font's are small (mainly the links). The color hex value is the right size, the `R:`, `G:`, `B:`, etc. is right.  The UI links are not, but that was done on purpose.  So it is a smaller scale in relation to your view's font, which is as expected. I was trying to make some of the UI stuff get out of the way to focus more on the color info.  Some of the dialogs can get quite big, so shrinking some of the UI helped get the size a little more reasonable.

> In my opinion, this should be a setting in a configuration

It was designed with mdpopups in mind (as I am the author of that), and everything is placed under the class `.color-helper` and other things have specific classes set to it like `.small`. So you, the user can override them in your `User/mdpopups.css` file.  So it **is** configurable.  That is how mdpopups is designed, so that the user gets the last say.  I don't like those links the same size as everything else, but everyone is different.  That's why I created mdpopups and gave the user the ability to override anything and everything via their own user CSS.

> I've run the command you have requested and it says that all the dependencies have been satisfied.

That should be fine.  That probably means you have the latest now.  I didn't expect it would change the behavior as I described above the the behavior is expected.  I just wanted to make sure you were on the latest.  Some old versions of mdpopups CSS loading is a bit different.  Just wanted to make sure you weren't sitting on an old version before you started messing with the CSS.

Anyways, it sounds like you just want all the UI elements to be the size of the view. Just create a `mdpopups.css` file in your `Packages/User` folder and add:

```css
.color-helper .small { font-size: 1rem; }
```

Tweak it to anything you like.
