### ISSUE TITLE
Quick flash of the popup when clicking the phantom

### ISSUE THREAD

**Issue by princemaple** [facelessuser/ColorHelper#41]
It seems that, clicking on the phantom triggers the popup immediately and also locates the cursor to the color string, which then triggers the second render of the popup.

I can't record a gif because the gap is quite small that it doesn't show in a gif...

**Comment by princemaple** [comment]
BTW the use of the new feature is awesome! Loving it.

**Comment by facelessuser** [comment]
I'm actually already aware of it, and it's actually the opposite.  The cursor moves, but the auto pop-up doesn't trigger and won't trigger.  So I then call the command directly to trigger the pop-up, but then Sublime decides to finally trigger the `on_modified_selection` event.  It's weird.

To be honest, I may remove the pop-up on selection when the inline preview is enabled and require clicking that instead of the text.  I'm on the fence which is why I haven't done it yet.

**Comment by facelessuser** [comment]
> BTW the use of the new feature is awesome! Loving it.

Glad you like it.  I want going to do anything like this until Phantoms came out, then I decided to change my mind as it is much better than gutter colors or highlighting text.

**Comment by princemaple** [comment]
The only thing it would affect me is, I rarely use the mouse. But any
operation on the popup requires mouse clicka anyway. I guess I can live
with that.

**Comment by facelessuser** [comment]
Which is also why I haven't changed it yet.  I may be able to briefly disable pop-up when I trigger it, but I didn't feel like messing with anymore and released it.  Most likely once I take a break I'll revisit the issue.

**Comment by princemaple** [comment]
:+1:

**Comment by facelessuser** [comment]
This should be resolved moving forward.

**Comment by princemaple** [comment]
Will you release a 2.0.4 for this?

**Comment by facelessuser** [comment]
When I get a chance.

**Comment by princemaple** [comment]
Sure, thanks :)
