### ISSUE TITLE
Version for Atom, please!

### ISSUE THREAD

**Issue by dlewand691** [facelessuser/ColorHelper#43]
Would it be possible to port this over for use in Atom? Would be a great addition. Thank you!

**Comment by facelessuser** [comment]
I do appreciate your interest as it is a compliment to the work done on this plugin.  Unfortunately, there is not much incentive for me to develop this for Atom.  One of the driving forces behind all my plugin development on Sublime is that I use the plugins; I don't make money off any of them.  Since I don't use Atom, I would essentially be investing a lot of time (which pulls me away from my family) developing (not even counting support once it is ported) for something I won't even be using.  As all of this is done in my free time, unless I start using Atom, I unfortunately will not be pursuing this.

I know there are a lot of talented Atom plugin developers out there, and hopefully one them will step up to the challenge of creating a similar tool.
