### ISSUE TITLE
user_color_scanning configuration

### ISSUE THREAD

**Issue by FichteFoll** [facelessuser/ColorHelper#60]
When you want to add scopes for Color Helper to scan, you need to duplicate the existing color_scanning rules into your user settings file. A procedure like in BracketHighlighter would be much appreciated for this package as well (referring to adding rules, not necessarily modifying existing ones).

**Comment by facelessuser** [comment]
Yes, this is planned, just haven't had the time yet.

**Comment by facelessuser** [comment]
Now that #158 is coming together, we can support new color spaces, users can override color spaces to provide new input and output formats, and the whole thing should be easier for me to maintain.

This is a prime time for me to tackle this as well to make ColorHelper easier to use and easier for me to maintain. This will probably be the biggest update since the release of ColorHelper.

**Comment by facelessuser** [comment]
`user_color_rules` is implemented. If a rule uses the same `name` key, a shallow merge will be applied allowing top level overrides. Otherwise, simply append to the bottom. Nothing too fancy, no inserting positions and stuff that BracketHighlighter does. Just wanted to keep it super simple.
