### ISSUE TITLE
Prevent reflow while editing

### ISSUE THREAD

**Issue by twolfson** [facelessuser/ColorHelper#64]
I am getting pretty frustrated at reading/editing code only to have it reflow on it me before I finish. Here's a demonstration of what I'm getting frustrated at:

![recording](https://cloud.githubusercontent.com/assets/902488/19294950/e84e8176-8fe5-11e6-8d40-9dad87e3c3da.gif)

Here are some ideas to solve the problem:
- Allow repositioning color to right
  - I saw that #46 originally had the feature to the right as did screenshots
  - https://github.com/facelessuser/ColorHelper/blob/st3-2.1.1/docs/images/inline_previews.png
- Place a placeholder block for a few seconds after deletion (e.g. loading spinner, stopwatch image)
- Leave same block up for a few seconds until user stops typing. Then, update it
  - I haven't fully read through code but this assumes it's not a performance issue when rewriting phantom value

**Comment by twolfson** [comment]
Updating description to "Prevent reflow while editing" as that's what is really frustrating me -- not left/right toggle

**Comment by facelessuser** [comment]
Currently this is what it does:

- When an edit occurs, it clears the phantoms affected.
- It then waits X amount of time between edits before redrawing edits.
- When the X amount of time between edits is achieved, it updates the missing previews in the visible region of the document.

So are you dissatisfied with the amount wait between edits? The clearing of the preview because it is located before the edited region and causes a shift of the current text (this shouldn't actually affect typing in anyway shape or form -- it would at most just be a personal preference thing to some)?

**Comment by twolfson** [comment]
I'm realizing that my GIF my not be clear about which frame comes first so I'll fix that. Here's a more obvious one:

![recording](https://cloud.githubusercontent.com/assets/902488/19301352/d4dde95a-9013-11e6-8ac4-2fa1b0511840.gif)

I'm dissatisfied about the current behavior -- not necessarily wait between edits. I listed some options to solve the problem (e.g. reposition phantom to right).

For a left-sided solution, I would expect the following behavior:

- User starts editing
- Timeout loop begins to detect when user stops editing
    - Similar to auto-complete behavior where we don't send a search query until we know someone is done editing or it's been Y seconds since last update
- User stops editing
- Clear affected phantoms
- Redraw phantoms

For more complex behavior (probably more natural):

- User starts editing
- Timeout loop checks to see how color-like edited region is
    - For example `#|` isn't too color like (e.g. could be markdown header) but `#33|`, `#3333|`, and `#33333|` are
    - More examples for `rgb` -- `rgb(0| 200, 300)` (no comma at cursor)
- If we have lost color close-ness, then erase phantom
    - This is emulating program detecting user intention to delete color or update it
- User stops editing
- Redraw phantoms

I don't follow what you mean by "edited region causes a shift of the current text". Can you elaborate?

**Comment by facelessuser** [comment]
> I'm dissatisfied about the current behavior -- not necessarily wait between edits. I listed some options to solve the problem (e.g. reposition phantom to right).

I'm still trying to understand your dissatisfaction.  I see the GIF, I understand what is occurring in the GIF.  But I am still trying to understand what part is annoying you.  In your image it erases the image when you edit (which I expect).  Then when you have finished, and have a valid color, it redraws.  What part is annoying?  Before I start considering solutions, I need to clearly understand the problem, and I currently don't.

> I don't follow what you mean by "edited region causes a shift of the current text". Can you elaborate?

This is me trying to interpret your problem.  Maybe I am not understanding still.

**Comment by twolfson** [comment]
My frustration is the text jumps visually (and as a result, the cursor too
visually) before I'm done editing.

I'm not sure about you but when I edit, I read the characters on screen as
I type them to make sure they were my intent (I'm a sloppy typist).

An analogy would be someone shakes a book while you are reading it. You can
find your place again but it would be easier if the shake didn't exist at
all

**Comment by facelessuser** [comment]
I'm not sure I see this as a big deal.  It does delete the color when editing, which makes sense as it is no longer valid. Can I delay the initial clear? sure, and maybe I'll look into to that.  It does wait to redraw it once consecutive edits slow down.  Maybe I'll add the option to put the color back to the right.  I'll have to see.  Probably not going to calculate color closeness though.

In generally I don't see this as a big problem, but I do understand that it may bother some.  I'll look into it, but it may be down the list as I do have some more pressing issues to resolve first when I get the time to work on this again.

**Comment by twolfson** [comment]
To reiterate, I'm fine with it deleting the color -- my main issue is the cursor jumps while I'm editing (i.e. a reflow occurs where I'm looking).

It sounds like adding an option to place previews on the right will be the simplest solution. I'm going to take a shot at this and possibly open a PR

**Comment by facelessuser** [comment]
I still don't understand what you mean by reflow.  I am assuming you mean recreate the preview?  That will only happen when there is a valid color **and** you have paused in your typing long enough.  On rare occasions you may pause and then start typing, it may redraw the color after you have typed more characters because there can be a lag as the operation is asynchronous, and it is working with a cached snippet of the working view window, but once it is done, it will remove invalids.  That is why I mentioned increasing the required pause may be perfectly fine and make it more usable for less proficient typists.  I like the color to the left as often it lines things up nicer **and** the preview is actually contained within the same region as the color simplifying logic.

It used to be on the right, but then I moved it to the left. Ideally, I want it one way or the other, but I need to think about how I want to proceed.  You are welcome to create a pull that reverts it to the old way and that will save me time if I choose to go that route, it won't change how and when the redraw occurs, but it will physically move it to the right and maybe for most situations alleviate the issue.  If you are doing multi-editing, you will still get cursor being moved.

**Comment by twolfson** [comment]
Could you explain why you want it to be consistently left/right for all users? It seems reasonable to let it be an option since there are users like me who want it on the right and users in #46 who want it on the left.

**Comment by facelessuser** [comment]
My preference is to have it one way so I don't have to check yet another variable that requires me to nuke all previews.  I'm not saying I won't allow it to be configurable, but I want to avoid it.  The more complexity I add, the more complexity I have to maintain.

There is quite a bit of rewriting I have to do on this to make it more polished and fix some general poor behavior.  This started out as a proof of concept that grew a bit larger than I had originally planned.  I maintain a lot of plugins right now.

**Comment by twolfson** [comment]
While I understand your maintenance concern, toggling left/right seems like a core feature (i.e. something that can't be handled by another plugin) whereas something like palette management could be offloaded to another package (not too sure how in the Sublime ecosystem). That's usually how I base whether to support functionality =/

**Comment by twolfson** [comment]
Alright, completed adding support for toggling since I was already half-way done with it. I've opened it as PR #65

**Comment by facelessuser** [comment]
> While I understand your maintenance concern, toggling left/right seems like a core feature (i.e. something that can't be handled by another plugin) whereas something like palette management could be offloaded to another package (not too sure how in the Sublime ecosystem). That's usually how I base whether to support functionality =/

Again, I'm not saying I won't allow it, I think I even eluded I may make it configurable, I just want to think about it.  I am a bit more selfish when it comes to my hobby projects.  I code what I want, and then I make it public for those who like it.  Sometimes I pass on features simply because I will never use them.  Essentially, projects like this, I view myself as the main customer.  That isn't to say I don't implement things people request, but usually I have some interest in the request.  

My approach varies on what I am supporting and how much time I am investing in the support of that project.  My approach for personal projects is different than it is for something commercial and even varies from personal project to personal project.  For instance, BracketHighlighter is my most popular plugin, and I've probably been the most flexible, and put in the most effort there because it is so popular.  In general, I think I am a lot more difficult to get motivated on certain requests compared to back when I had two plugins I was maintaining.

Anyways, this plugin has been becoming more and more popular, and I am gearing up for a big rewrite of a lot of the code to make it more flexible, stable, and easier to maintain.  Not sure when that will happen yet because it will eat up a lot of free time.
