### ISSUE TITLE
Broken support for CSS3 package

### ISSUE THREAD

**Issue by megema** [facelessuser/ColorHelper#73]
## Description

ColorHelper is not working with the CSS3 package's syntax, however the default configuration contains lines reffering to it.

## Support Info

- ST ver.: 3126
- Platform: osx
- Arch: x64
- Plugin ver.: 2.3.0
- Install via PC: True
- mdpopups ver.: 1.13.1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

1. Open a CSS file
2. Install CSS3 package
3. Switch to CSS3 syntax

**Comment by facelessuser** [comment]
Yup.  Can't help it if CSS3 changes how they do things.  Eventually I am going to restructure this code so I can have a rule that for that targets each specific syntax file.  That way when it breaks, it will be obvious what needs to be changed so that the community can keep this stuff up to date.

I will take a look when I get a chance.  I will more view this as a feature request to support latest CSS3 syntax file.
