### ISSUE TITLE
Remove borders around colors on picker

### ISSUE THREAD

**Issue by mkormendy** [facelessuser/ColorHelper#99]
## Description

The picker would benefit from having the option to remove the white/black border frame around each color that is in the picker.

**Comment by facelessuser** [comment]
This is already planned.

The only reason it was done the current way is because there is no way to tell what the background of the popup is.  Themes can actually override the background as well as the user, so a double border was selected that ensures colors won't blend into the background. But the borders are so harsh it can detract from the color preview.

Anyways, I won't eliminate the border altogether as similar colors will all blend into to each other, but I will specify a single border with a default that is slightly different enough from what the background is **supposed** to be (assuming it hasn't been overridden with something weird).  After a theme or user modifies the popup background to something weird, it will be out of my hands.

**Comment by mkormendy** [comment]
I think putting an option to have a border, light, dark, or none in the settings would be the best outcome as the user can turn it off or on, and if they have some custom theme they can figure it out for themselves.

**Comment by facelessuser** [comment]
I'll play with options and see what I am comfortable with. I've been pretty busy recently, but hopefully I'll get around to addressing it sometime soonish.

**Comment by facelessuser** [comment]
So the plan is probably to use CSS borders instead of generating the image with borders as currently done. CSS would have been used from the start, but the minihtml environment did not support borders at the time this was implemented. This will allow a user to override the color of desired.

**Comment by mkormendy** [comment]
Would it also be possible to add a hover state with the minihtml css that enlarges the color when the user hovers over any specific color, so that there's an intuitive way to know which color is being hovered over specifically before clicking it? Maybe by using the font-size for the color item?

**Comment by facelessuser** [comment]
Borders overall are greatly reduced, and in the case of the hex color wheels, they are removed.

**Comment by mkormendy** [comment]
@facelessuser very nice! Thank you for following up with this.

**Comment by facelessuser** [comment]
Better late than never :)
